library(dplyr)

# load the list of observations
data_test  <- as.data.frame(matrix(scan("test/X_test.txt"), ncol = 561, byrow=TRUE))
data_train <- as.data.frame(matrix(scan("train/X_train.txt"), ncol = 561, byrow=TRUE))

# add on the activity # column of each
activities <- read.table("activity_labels.txt")
data_test  <- cbind(data_test, activity = activities[scan("test/y_test.txt", what = integer()), 2])
data_train <- cbind(data_train, activity = activities[scan("train/y_train.txt", what = integer()), 2])

# add on the subject # column for each
data_test  <- cbind(data_test, subject = scan("test/subject_test.txt", what = integer()))
data_train <- cbind(data_train, subject = scan("train/subject_train.txt", what = integer()))

# combine into a single data set
data <- rbind(data_train, data_test)

# rename the variables we want
tbl <- tbl_df(data)
tbl <- rename(tbl, 
              time_body_accelerometer_mean_X = V1, 
              time_body_accelerometer_mean_Y = V2, 
              time_body_accelerometer_mean_Z = V3, 
              time_body_accelerometer_std_X = V4, 
              time_body_accelerometer_std_Y = V5, 
              time_body_accelerometer_std_Z = V6,
              time_gravity_accelerometer_mean_X = V41,
              time_gravity_accelerometer_mean_Y = V42,
              time_gravity_accelerometer_mean_Z = V43,
              time_gravity_accelerometer_std_X = V44,
              time_gravity_accelerometer_std_Y = V45,
              time_gravity_accelerometer_std_Z = V46,
              time_body_accelerometer_jerk_mean_X = V81,
              time_body_accelerometer_jerk_mean_Y = V82,
              time_body_accelerometer_jerk_mean_Z = V83,
              time_body_accelerometer_jerk_std_X = V84,
              time_body_accelerometer_jerk_std_Y = V85,
              time_body_accelerometer_jerk_std_Z = V86,
              time_body_gyroscope_mean_X = V121,
              time_body_gyroscope_mean_Y = V122,
              time_body_gyroscope_mean_Z = V123,
              time_body_gyroscope_std_X = V124,
              time_body_gyroscope_std_Y = V125,
              time_body_gyroscope_std_Z = V126,
              time_body_gyroscope_jerk_mean_X = V161,
              time_body_gyroscope_jerk_mean_Y = V162,
              time_body_gyroscope_jerk_mean_Z = V163,
              time_body_gyroscope_jerk_std_X = V164,
              time_body_gyroscope_jerk_std_Y = V165,
              time_body_gyroscope_jerk_std_Z = V166,
              time_body_accelerometer_magnitute_mean = V201,
              time_body_accelerometer_magnitute_std = V202,
              time_gravity_accelerometer_magnitute_mean = V214,
              time_gravity_accelerometer_magnitute_std = V215,
              time_body_accelerometer_jerk_magnitute_mean = V227,
              time_body_accelerometer_jerk_magnitute_std = V228,
              time_body_gyroscope_magnitute_mean = V240,
              time_body_gyroscope_magnitute_std = V241,
              time_body_gyroscope_jerk_magnitute_mean = V253,
              time_body_gyroscope_jerk_magnitute_std = V254,
              frequency_body_accelerometer_mean_X = V266,
              frequency_body_accelerometer_mean_Y = V267,
              frequency_body_accelerometer_mean_Z = V268,
              frequency_body_accelerometer_std_X = V269,
              frequency_body_accelerometer_std_Y = V270,
              frequency_body_accelerometer_std_Z = V271,
              frequency_body_accelerometer_jerk_mean_X = V345,
              frequency_body_accelerometer_jerk_mean_Y = V346,
              frequency_body_accelerometer_jerk_mean_Z = V347,
              frequency_body_accelerometer_jerk_std_X = V348,
              frequency_body_accelerometer_jerk_std_Y = V349,
              frequency_body_accelerometer_jerk_std_Z = V350,
              frequency_body_gyroscope_mean_X = V424,
              frequency_body_gyroscope_mean_Y = V425,
              frequency_body_gyroscope_mean_Z = V426,
              frequency_body_gyroscope_std_X = V427,
              frequency_body_gyroscope_std_Y = V428,
              frequency_body_gyroscope_std_Z = V429,
              frequency_body_accelerometer_magnitute_mean = V503,
              frequency_body_accelerometer_magnitute_std = V504,
              frequency_body_accelerometer_jerk_magnitute_mean = V516,
              frequency_body_accelerometer_jerk_magnitute_std = V517,
              frequency_body_gyroscope_magnitute_mean = V529,
              frequency_body_gyroscope_magnitute_std = V530,
              frequency_body_gyroscope_jerk_magnitute_mean = V542,
              frequency_body_gyroscope_jerk_magnitute_std = V543
              )

# extract only the variables we want
tbl <- select(tbl, 
              subject,
              activity,
              time_body_accelerometer_mean_X, 
              time_body_accelerometer_mean_Y, 
              time_body_accelerometer_mean_Z, 
              time_body_accelerometer_std_X, 
              time_body_accelerometer_std_Y, 
              time_body_accelerometer_std_Z,
              time_gravity_accelerometer_mean_X,
              time_gravity_accelerometer_mean_Y,
              time_gravity_accelerometer_mean_Z,
              time_gravity_accelerometer_std_X,
              time_gravity_accelerometer_std_Y,
              time_gravity_accelerometer_std_Z,
              time_body_accelerometer_jerk_mean_X,
              time_body_accelerometer_jerk_mean_Y,
              time_body_accelerometer_jerk_mean_Z,
              time_body_accelerometer_jerk_std_X,
              time_body_accelerometer_jerk_std_Y,
              time_body_accelerometer_jerk_std_Z,
              time_body_gyroscope_mean_X,
              time_body_gyroscope_mean_Y,
              time_body_gyroscope_mean_Z,
              time_body_gyroscope_std_X,
              time_body_gyroscope_std_Y,
              time_body_gyroscope_std_Z,
              time_body_gyroscope_jerk_mean_X,
              time_body_gyroscope_jerk_mean_Y,
              time_body_gyroscope_jerk_mean_Z,
              time_body_gyroscope_jerk_std_X,
              time_body_gyroscope_jerk_std_Y,
              time_body_gyroscope_jerk_std_Z,
              time_body_accelerometer_magnitute_mean,
              time_body_accelerometer_magnitute_std,
              time_gravity_accelerometer_magnitute_mean,
              time_gravity_accelerometer_magnitute_std,
              time_body_accelerometer_jerk_magnitute_mean,
              time_body_accelerometer_jerk_magnitute_std,
              time_body_gyroscope_magnitute_mean,
              time_body_gyroscope_magnitute_std,
              time_body_gyroscope_jerk_magnitute_mean,
              time_body_gyroscope_jerk_magnitute_std,
              frequency_body_accelerometer_mean_X,
              frequency_body_accelerometer_mean_Y,
              frequency_body_accelerometer_mean_Z,
              frequency_body_accelerometer_std_X,
              frequency_body_accelerometer_std_Y,
              frequency_body_accelerometer_std_Z,
              frequency_body_accelerometer_jerk_mean_X,
              frequency_body_accelerometer_jerk_mean_Y,
              frequency_body_accelerometer_jerk_mean_Z,
              frequency_body_accelerometer_jerk_std_X,
              frequency_body_accelerometer_jerk_std_Y,
              frequency_body_accelerometer_jerk_std_Z,
              frequency_body_gyroscope_mean_X,
              frequency_body_gyroscope_mean_Y,
              frequency_body_gyroscope_mean_Z,
              frequency_body_gyroscope_std_X,
              frequency_body_gyroscope_std_Y,
              frequency_body_gyroscope_std_Z,
              frequency_body_accelerometer_magnitute_mean,
              frequency_body_accelerometer_magnitute_std,
              frequency_body_accelerometer_jerk_magnitute_mean,
              frequency_body_accelerometer_jerk_magnitute_std,
              frequency_body_gyroscope_magnitute_mean,
              frequency_body_gyroscope_magnitute_std,
              frequency_body_gyroscope_jerk_magnitute_mean,
              frequency_body_gyroscope_jerk_magnitute_std
)

# create our tidy dataset by summarizing the variables we want
tidy <- summarize(group_by(tbl, subject, activity), 
               time_body_accelerometer_mean_X = mean(time_body_accelerometer_mean_X), 
               time_body_accelerometer_mean_Y = mean(time_body_accelerometer_mean_Y), 
               time_body_accelerometer_mean_Z = mean(time_body_accelerometer_mean_Z), 
               time_body_accelerometer_std_X = mean(time_body_accelerometer_std_X), 
               time_body_accelerometer_std_Y = mean(time_body_accelerometer_std_Y), 
               time_body_accelerometer_std_Z = mean(time_body_accelerometer_std_Z),
               time_gravity_accelerometer_mean_X = mean(time_gravity_accelerometer_mean_X),
               time_gravity_accelerometer_mean_Y = mean(time_gravity_accelerometer_mean_Y),
               time_gravity_accelerometer_mean_Z = mean(time_gravity_accelerometer_mean_Z),
               time_gravity_accelerometer_std_X = mean(time_gravity_accelerometer_std_X),
               time_gravity_accelerometer_std_Y = mean(time_gravity_accelerometer_std_Y),
               time_gravity_accelerometer_std_Z = mean(time_gravity_accelerometer_std_Z),
               time_body_accelerometer_jerk_mean_X = mean(time_body_accelerometer_jerk_mean_X),
               time_body_accelerometer_jerk_mean_Y = mean(time_body_accelerometer_jerk_mean_Y),
               time_body_accelerometer_jerk_mean_Z = mean(time_body_accelerometer_jerk_mean_Z),
               time_body_accelerometer_jerk_std_X = mean(time_body_accelerometer_jerk_std_X),
               time_body_accelerometer_jerk_std_Y = mean(time_body_accelerometer_jerk_std_Y),
               time_body_accelerometer_jerk_std_Z = mean(time_body_accelerometer_jerk_std_Z),
               time_body_gyroscope_mean_X = mean(time_body_gyroscope_mean_X),
               time_body_gyroscope_mean_Y = mean(time_body_gyroscope_mean_Y),
               time_body_gyroscope_mean_Z = mean(time_body_gyroscope_mean_Z),
               time_body_gyroscope_std_X = mean(time_body_gyroscope_std_X),
               time_body_gyroscope_std_Y = mean(time_body_gyroscope_std_Y),
               time_body_gyroscope_std_Z = mean(time_body_gyroscope_std_Z),
               time_body_gyroscope_jerk_mean_X = mean(time_body_gyroscope_jerk_mean_X),
               time_body_gyroscope_jerk_mean_Y = mean(time_body_gyroscope_jerk_mean_Y),
               time_body_gyroscope_jerk_mean_Z = mean(time_body_gyroscope_jerk_mean_Z),
               time_body_gyroscope_jerk_std_X = mean(time_body_gyroscope_jerk_std_X),
               time_body_gyroscope_jerk_std_Y = mean(time_body_gyroscope_jerk_std_Y),
               time_body_gyroscope_jerk_std_Z = mean(time_body_gyroscope_jerk_std_Z),
               time_body_accelerometer_magnitute_mean = mean(time_body_accelerometer_magnitute_mean),
               time_body_accelerometer_magnitute_std = mean(time_body_accelerometer_magnitute_std),
               time_gravity_accelerometer_magnitute_mean = mean(time_gravity_accelerometer_magnitute_mean),
               time_gravity_accelerometer_magnitute_std = mean(time_gravity_accelerometer_magnitute_std),
               time_body_accelerometer_jerk_magnitute_mean = mean(time_body_accelerometer_jerk_magnitute_mean),
               time_body_accelerometer_jerk_magnitute_std = mean(time_body_accelerometer_jerk_magnitute_std),
               time_body_gyroscope_magnitute_mean = mean(time_body_gyroscope_magnitute_mean),
               time_body_gyroscope_magnitute_std = mean(time_body_gyroscope_magnitute_std),
               time_body_gyroscope_jerk_magnitute_mean = mean(time_body_gyroscope_jerk_magnitute_mean),
               time_body_gyroscope_jerk_magnitute_std = mean(time_body_gyroscope_jerk_magnitute_std),
               frequency_body_accelerometer_mean_X = mean(frequency_body_accelerometer_mean_X),
               frequency_body_accelerometer_mean_Y = mean(frequency_body_accelerometer_mean_Y),
               frequency_body_accelerometer_mean_Z = mean(frequency_body_accelerometer_mean_Z),
               frequency_body_accelerometer_std_X = mean(frequency_body_accelerometer_std_X),
               frequency_body_accelerometer_std_Y = mean(frequency_body_accelerometer_std_Y),
               frequency_body_accelerometer_std_Z = mean(frequency_body_accelerometer_std_Z),
               frequency_body_accelerometer_jerk_mean_X = mean(frequency_body_accelerometer_jerk_mean_X),
               frequency_body_accelerometer_jerk_mean_Y = mean(frequency_body_accelerometer_jerk_mean_Y),
               frequency_body_accelerometer_jerk_mean_Z = mean(frequency_body_accelerometer_jerk_mean_Z),
               frequency_body_accelerometer_jerk_std_X = mean(frequency_body_accelerometer_jerk_std_X),
               frequency_body_accelerometer_jerk_std_Y = mean(frequency_body_accelerometer_jerk_std_Y),
               frequency_body_accelerometer_jerk_std_Z = mean(frequency_body_accelerometer_jerk_std_Z),
               frequency_body_gyroscope_mean_X = mean(frequency_body_gyroscope_mean_X),
               frequency_body_gyroscope_mean_Y = mean(frequency_body_gyroscope_mean_Y),
               frequency_body_gyroscope_mean_Z = mean(frequency_body_gyroscope_mean_Z),
               frequency_body_gyroscope_std_X = mean(frequency_body_gyroscope_std_X),
               frequency_body_gyroscope_std_Y = mean(frequency_body_gyroscope_std_Y),
               frequency_body_gyroscope_std_Z = mean(frequency_body_gyroscope_std_Z),
               frequency_body_accelerometer_magnitute_mean = mean(frequency_body_accelerometer_magnitute_mean),
               frequency_body_accelerometer_magnitute_std = mean(frequency_body_accelerometer_magnitute_std),
               frequency_body_accelerometer_jerk_magnitute_mean = mean(frequency_body_accelerometer_jerk_magnitute_mean),
               frequency_body_accelerometer_jerk_magnitute_std = mean(frequency_body_accelerometer_jerk_magnitute_std),
               frequency_body_gyroscope_magnitute_mean = mean(frequency_body_gyroscope_magnitute_mean),
               frequency_body_gyroscope_magnitute_std = mean(frequency_body_gyroscope_magnitute_std),
               frequency_body_gyroscope_jerk_magnitute_mean = mean(frequency_body_gyroscope_jerk_magnitute_mean),
               frequency_body_gyroscope_jerk_magnitute_std = mean(frequency_body_gyroscope_jerk_magnitute_std)
)

tidy
